import React from 'react';
import { X, Download, FileSpreadsheet, FileJson, Printer, Database, MessageSquare } from 'lucide-react';
import { MatchedPair, ReconciliationMetrics, ReconciliationDataset } from '../types/reconciliation';

interface ExportModalProps {
  isOpen: boolean;
  onClose: () => void;
  dataset: ReconciliationDataset;
  matchedPairs: MatchedPair[];
  metrics: ReconciliationMetrics;
  onOpenSupabase?: () => void;
  onOpenSlack?: () => void;
}

export const ExportModal: React.FC<ExportModalProps> = ({
  isOpen,
  onClose,
  dataset,
  matchedPairs,
  metrics,
  onOpenSupabase,
  onOpenSlack
}) => {
  if (!isOpen) return null;

  const exportReconciledCSV = () => {
    const headers = [
      'Match_ID',
      'Tier',
      'Confidence_Pct',
      'Bank_Tx_IDs',
      'Bank_Total',
      'Ledger_Tx_IDs',
      'Ledger_Total',
      'Variance',
      'Status',
      'Summary_Reasoning',
      'Auditor_Notes'
    ];

    const rows = matchedPairs
      .filter(p => p.tier !== 'UNMATCHED')
      .map(p => [
        p.id,
        p.tier,
        p.confidence,
        `"${p.bankTxIds.join(';')}"`,
        p.bankTotal,
        `"${p.ledgerTxIds.join(';')}"`,
        p.ledgerTotal,
        p.variance,
        p.status,
        `"${p.reasoning.summary.replace(/"/g, '""')}"`,
        `"${(p.auditorNotes || '').replace(/"/g, '""')}"`
      ]);

    const csvContent = [headers.join(','), ...rows.map(r => r.join(','))].join('\n');
    downloadFile(csvContent, `${dataset.id}-reconciled-ledger.csv`, 'text/csv');
  };

  const exportExceptionsCSV = () => {
    const headers = [
      'Exception_ID',
      'Category',
      'Bank_Amount',
      'Ledger_Amount',
      'Variance',
      'AI_Explanation',
      'Recommended_Action'
    ];

    const rows = matchedPairs
      .filter(p => p.tier === 'UNMATCHED')
      .map(p => [
        p.id,
        p.exceptionType || 'UNMATCHED',
        p.bankTotal,
        p.ledgerTotal,
        p.variance,
        `"${p.reasoning.summary.replace(/"/g, '""')}"`,
        `"${(p.reasoning.suggestedAction || '').replace(/"/g, '""')}"`
      ]);

    const csvContent = [headers.join(','), ...rows.map(r => r.join(','))].join('\n');
    downloadFile(csvContent, `${dataset.id}-exceptions-binder.csv`, 'text/csv');
  };

  const exportFullJSON = () => {
    const exportData = {
      dataset: {
        id: dataset.id,
        name: dataset.name,
        bank: dataset.bankName,
        ledger: dataset.ledgerName,
        currency: dataset.currency
      },
      generatedAt: new Date().toISOString(),
      metrics,
      matchedPairs
    };
    downloadFile(JSON.stringify(exportData, null, 2), `${dataset.id}-audit-pack.json`, 'application/json');
  };

  const printAuditCertificate = () => {
    const printWindow = window.open('', '_blank');
    if (!printWindow) return;

    const html = `
      <!DOCTYPE html>
      <html>
      <head>
        <title>Month-End Reconciliation Certificate - ${dataset.name}</title>
        <style>
          body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; padding: 40px; color: #1e293b; }
          .header { border-bottom: 2px solid #0f172a; padding-bottom: 20px; margin-bottom: 24px; }
          .title { font-size: 24px; font-weight: 800; }
          .sub { color: #64748b; font-size: 14px; margin-top: 4px; }
          .grid { display: grid; grid-template-columns: repeat(4, 1fr); gap: 16px; margin: 24px 0; }
          .card { background: #f8fafc; border: 1px solid #e2e8f0; padding: 16px; border-radius: 8px; }
          .label { font-size: 11px; text-transform: uppercase; color: #64748b; font-weight: 700; }
          .val { font-size: 20px; font-weight: 800; margin-top: 4px; color: #0f172a; font-family: monospace; }
          table { width: 100%; border-collapse: collapse; margin-top: 24px; font-size: 12px; }
          th, td { border: 1px solid #e2e8f0; padding: 8px 12px; text-align: left; }
          th { background: #f1f5f9; }
          .sig-box { margin-top: 60px; display: grid; grid-template-columns: 1fr 1fr; gap: 40px; }
          .sig-line { border-top: 1px solid #0f172a; padding-top: 8px; font-size: 12px; }
        </style>
      </head>
      <body>
        <div class="header">
          <div class="title">MONTH-END FINANCIAL RECONCILIATION CERTIFICATE</div>
          <div class="sub">Generated by Tick &amp; Tie Autonomous AI Reconciliation Agent &bull; ${new Date().toLocaleDateString()}</div>
          <div class="sub">Dataset: ${dataset.name} (${dataset.currency}) | Bank: ${dataset.bankName} | Ledger: ${dataset.ledgerName}</div>
        </div>

        <div class="grid">
          <div class="card">
            <div class="label">Reconciliation Rate</div>
            <div class="val">${metrics.reconciliationRate.toFixed(1)}%</div>
          </div>
          <div class="card">
            <div class="label">Reconciled Volume</div>
            <div class="val">${dataset.currency} ${metrics.reconciledVolume.toLocaleString()}</div>
          </div>
          <div class="card">
            <div class="label">Net Book Variance</div>
            <div class="val">${dataset.currency} ${metrics.netVariance.toFixed(2)}</div>
          </div>
          <div class="card">
            <div class="label">Open Exceptions</div>
            <div class="val">${metrics.tierCounts.exceptions} Items</div>
          </div>
        </div>

        <h3>Tier Breakdown &amp; Verification Methodology</h3>
        <table>
          <thead>
            <tr>
              <th>Verification Tier</th>
              <th>Count</th>
              <th>Methodology</th>
              <th>Status</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td>Tier 1: Exact Deterministic Match</td>
              <td>${metrics.tierCounts.exact}</td>
              <td>Identical amount, date, and reference keys</td>
              <td>Verified 100%</td>
            </tr>
            <tr>
              <td>Tier 2: Heuristic &amp; Fuzzy Rules</td>
              <td>${metrics.tierCounts.heuristic}</td>
              <td>Settlement lag window, penny drift, standard gateway fee offsets</td>
              <td>Verified (85-96%)</td>
            </tr>
            <tr>
              <td>Tier 3: AI Semantic Reasoner</td>
              <td>${metrics.tierCounts.aiSemantic}</td>
              <td>Batch settlement split solver &amp; entity resolution</td>
              <td>AI Verified</td>
            </tr>
            <tr>
              <td>Tier 4: Honest Exceptions</td>
              <td>${metrics.tierCounts.exceptions}</td>
              <td>Timing lag, unrecorded bank fees, duplicate risks</td>
              <td>Pending Review</td>
            </tr>
          </tbody>
        </table>

        <div class="sig-box">
          <div>
            <div style="height: 40px;"></div>
            <div class="sig-line">Prepared By: Autonomous AI CPA Agent (Antigravity v2.6)</div>
          </div>
          <div>
            <div style="height: 40px;"></div>
            <div class="sig-line">Approved By: Corporate Controller / Chief Financial Officer</div>
          </div>
        </div>
      </body>
      </html>
    `;

    printWindow.document.write(html);
    printWindow.document.close();
    printWindow.focus();
    setTimeout(() => printWindow.print(), 250);
  };

  const downloadFile = (content: string, filename: string, mimeType: string) => {
    const blob = new Blob([content], { type: mimeType });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = filename;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  return (
    <div className="modal-backdrop" onClick={onClose}>
      <div className="modal-dialog" onClick={e => e.stopPropagation()}>
        <div className="modal-header">
          <div style={{ display: 'flex', alignItems: 'center', gap: '0.6rem' }}>
            <Download size={20} style={{ color: 'var(--accent-primary)' }} />
            <h3 className="modal-title">Export Compliance &amp; Close Pack</h3>
          </div>
          <button className="btn-icon-close" onClick={onClose}>
            <X size={20} />
          </button>
        </div>

        <div className="modal-body">
          <p style={{ fontSize: '0.82rem', color: 'var(--text-secondary)' }}>
            Download complete audit workpapers for your auditors, tax advisors, and leadership team.
            Every matched pair includes full chain-of-thought reasoning and variance calculations.
          </p>

          <div style={{ display: 'flex', flexDirection: 'column', gap: '0.75rem' }}>
            {/* 1. Reconciled CSV */}
            <div
              style={{
                display: 'flex',
                alignItems: 'center',
                justifyContent: 'space-between',
                padding: '0.85rem 1rem',
                background: 'var(--bg-surface-elevated)',
                borderRadius: 'var(--radius-md)',
                border: '1px solid var(--border-subtle)'
              }}
            >
              <div style={{ display: 'flex', alignItems: 'center', gap: '0.75rem' }}>
                <FileSpreadsheet size={24} style={{ color: 'var(--color-exact)' }} />
                <div>
                  <div style={{ fontSize: '0.85rem', fontWeight: 600 }}>Reconciled Transactions Sheet (CSV)</div>
                  <div style={{ fontSize: '0.72rem', color: 'var(--text-muted)' }}>
                    All verified exact, heuristic, and AI semantic pairs with variance &amp; notes
                  </div>
                </div>
              </div>
              <button className="btn btn-secondary" onClick={exportReconciledCSV}>
                <Download size={14} />
                <span>Download</span>
              </button>
            </div>

            {/* 2. Exception Sheet */}
            <div
              style={{
                display: 'flex',
                alignItems: 'center',
                justifyContent: 'space-between',
                padding: '0.85rem 1rem',
                background: 'var(--bg-surface-elevated)',
                borderRadius: 'var(--radius-md)',
                border: '1px solid var(--border-subtle)'
              }}
            >
              <div style={{ display: 'flex', alignItems: 'center', gap: '0.75rem' }}>
                <FileSpreadsheet size={24} style={{ color: 'var(--color-exception)' }} />
                <div>
                  <div style={{ fontSize: '0.85rem', fontWeight: 600 }}>Honest Exceptions Binder (CSV)</div>
                  <div style={{ fontSize: '0.72rem', color: 'var(--text-muted)' }}>
                    Unmatched items, timing differences, fees, and duplicate alerts
                  </div>
                </div>
              </div>
              <button className="btn btn-secondary" onClick={exportExceptionsCSV}>
                <Download size={14} />
                <span>Download</span>
              </button>
            </div>

            {/* 3. Full JSON Pack */}
            <div
              style={{
                display: 'flex',
                alignItems: 'center',
                justifyContent: 'space-between',
                padding: '0.85rem 1rem',
                background: 'var(--bg-surface-elevated)',
                borderRadius: 'var(--radius-md)',
                border: '1px solid var(--border-subtle)'
              }}
            >
              <div style={{ display: 'flex', alignItems: 'center', gap: '0.75rem' }}>
                <FileJson size={24} style={{ color: 'var(--accent-primary)' }} />
                <div>
                  <div style={{ fontSize: '0.85rem', fontWeight: 600 }}>Full Audit Workpack (JSON)</div>
                  <div style={{ fontSize: '0.72rem', color: 'var(--text-muted)' }}>
                    Machine-readable complete audit trail with full LLM chains-of-thought
                  </div>
                </div>
              </div>
              <button className="btn btn-secondary" onClick={exportFullJSON}>
                <Download size={14} />
                <span>Download</span>
              </button>
            </div>

            {/* 4. Formal Certificate */}
            <div
              style={{
                display: 'flex',
                alignItems: 'center',
                justifyContent: 'space-between',
                padding: '0.85rem 1rem',
                background: 'var(--bg-surface-elevated)',
                borderRadius: 'var(--radius-md)',
                border: '1px solid var(--border-subtle)'
              }}
            >
              <div style={{ display: 'flex', alignItems: 'center', gap: '0.75rem' }}>
                <Printer size={24} style={{ color: '#38bdf8' }} />
                <div>
                  <div style={{ fontSize: '0.85rem', fontWeight: 600 }}>Month-End Audit Certificate (PDF)</div>
                  <div style={{ fontSize: '0.72rem', color: 'var(--text-muted)' }}>
                    Formal sign-off certificate formatted for controller &amp; CFO review
                  </div>
                </div>
              </div>
              <button className="btn btn-primary" onClick={printAuditCertificate}>
                <Printer size={14} />
                <span>Print Certificate</span>
              </button>
            </div>

            {/* 5. Supabase Cloud Vault Sync */}
            {onOpenSupabase && (
              <div
                style={{
                  display: 'flex',
                  alignItems: 'center',
                  justifyContent: 'space-between',
                  padding: '0.85rem 1rem',
                  background: 'rgba(62, 207, 142, 0.05)',
                  borderRadius: 'var(--radius-md)',
                  border: '1px solid rgba(62, 207, 142, 0.3)'
                }}
              >
                <div style={{ display: 'flex', alignItems: 'center', gap: '0.75rem' }}>
                  <Database size={24} style={{ color: '#10b981' }} />
                  <div>
                    <div style={{ fontSize: '0.85rem', fontWeight: 600, color: '#047857' }}>
                      Supabase Cloud Audit Vault (PostgreSQL)
                    </div>
                    <div style={{ fontSize: '0.72rem', color: 'var(--text-muted)' }}>
                      Persist run record, compliance metrics, and exceptions table in cloud database
                    </div>
                  </div>
                </div>
                <button
                  className="btn btn-secondary"
                  onClick={() => {
                    onClose();
                    onOpenSupabase();
                  }}
                  style={{ borderColor: '#10b981', color: '#047857' }}
                >
                  <Database size={14} />
                  <span>Sync to Supabase</span>
                </button>
              </div>
            )}

            {/* 6. Slack Financial Close Broadcast */}
            {onOpenSlack && (
              <div
                style={{
                  display: 'flex',
                  alignItems: 'center',
                  justifyContent: 'space-between',
                  padding: '0.85rem 1rem',
                  background: 'rgba(74, 21, 75, 0.05)',
                  borderRadius: 'var(--radius-md)',
                  border: '1px solid rgba(74, 21, 75, 0.25)'
                }}
              >
                <div style={{ display: 'flex', alignItems: 'center', gap: '0.75rem' }}>
                  <MessageSquare size={24} style={{ color: '#ECB22E' }} />
                  <div>
                    <div style={{ fontSize: '0.85rem', fontWeight: 600, color: '#4A154B' }}>
                      Slack Month-End Close Broadcast
                    </div>
                    <div style={{ fontSize: '0.72rem', color: 'var(--text-muted)' }}>
                      Send formatted Block Kit close summary to #finance-close channel
                    </div>
                  </div>
                </div>
                <button
                  className="btn btn-secondary"
                  onClick={() => {
                    onClose();
                    onOpenSlack();
                  }}
                  style={{ borderColor: '#4A154B', color: '#4A154B' }}
                >
                  <MessageSquare size={14} />
                  <span>Notify on Slack</span>
                </button>
              </div>
            )}
          </div>
        </div>

        <div className="modal-footer">
          <button className="btn btn-outline" onClick={onClose}>
            Close
          </button>
        </div>
      </div>
    </div>
  );
};
